name: dio_network_config

packages:
  - packages/**
  - cli

ide:
  intellij: true

scripts:
  # Bootstrap all packages (cross-platform Dart script)
  bootstrap:
    run: dart bootstrap.dart
    description: Bootstrap all packages by getting their dependencies

  # Clean all packages
  clean:
    run: |
      for dir in packages/*/; do
        if [ -f "$dir/pubspec.yaml" ]; then
          echo "Cleaning ${dir%/}"
          cd "$dir" && flutter clean && cd - > /dev/null
        fi
      done
    description: Clean all packages

  # Get dependencies (same as bootstrap)
  get:
    run: dart bootstrap.dart
    description: Get dependencies for all packages

  # Analyze all packages
  analyze:
    run: melos exec -- "flutter analyze --no-fatal-infos"
    description: Analyze all packages

  # Format code
  format:
    run: melos exec -- "dart format ."
    description: Format all Dart code

  # Run tests
  test:
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run tests in all packages

  # Run app
  run:app:
    run: cd packages/app && flutter run
    description: Run the main application
